### ISSUE TITLE
XAPI should work with endpoint config whether or not the endpoint includes trailing /

### ISSUE THREAD

**Issue by beatthat** [xapijs/xapi#103]
The current XAPI impl takes an `endpoint` param and assumes the endpoint as a trailing slash included. If you create XAPI with an `endpoint` that doesn't include the trailing slash, all XAPI-resource urls will be broken

Added a quick PR for this with an attempt to startup some tests that run independent of any real/external xapi server. Let me know what you think.

**Comment by CookieCookson** [comment]
Fixed in https://github.com/xapijs/xapi/pull/104
