### ISSUE TITLE
Module parse failed: Unexpected token (1:17691) in @xapi/xapi/dist/XAPI.umd.js

### ISSUE THREAD

**Issue by letsgo0** [xapijs/xapi#146]
**situation**: i use vue3 to create a project. and i exceute "npm run serve".
 it “ **Failed to compile with 1 error**   ”. （The specific error information is listed below）
i am confused about the syntax about '?' in the xxx.umd.js.  could someone tell my how to do with that.
e.g 
`sendStatement(e, n) {  if (`**n?.length**`) { const o = function (e, t) { const n = [], o = (Math.random() + " ").substring(2, 10) + (Math.random() + " ").substring(2, 10), a = { "Content-Type": "multipart/mixed; boundary=" + o }, i = ["--" + o, "Content-Type: application/json", 'Content-Disposition: form-data; name="statement"', "", JSON.stringify(e)].join(r) + r; return n.push(i), t.forEach((t, a) => { const i = e.attachments[a], s = ["--" + o, "Content-Type: " + i.contentType, "Content-Transfer-Encoding: binary", "X-Experience-API-Hash: " + i.sha2].join(r) + r + r; n.push(s), n.push(t) }), n.push(`\r\n--${o}--\r\n`), { header: a, blob: new Blob(n) } }(e, n); return this.requestResource(t.STATEMENT, {}, { method: "POST", headers: o.header, data: o.blob }) } return this.requestResource(t.STATEMENT, {}, { method: "POST", data: e }) }`

Failed to compile with 1 error     
Module parse failed: Unexpected token (1:17691)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders     
> 
`!function (e, t) { "object" == typeof exports && "undefined" != typeof module ? module.exports = t() : "function" == typeof define && define.amd ? define(t) : (e = "undefined" != typeof globalThis ? globalThis : e || self).XAPI = t() }(this, (function () { "use strict"; let e, t; !function (e) { e.SIGNATURE = "http://adlnet.gov/expapi/attachments/signature", e.CERTIFICATE_OF_COMPLETION = "http://id.tincanapi.com/attachment/certificate-of-completion", e.CONTRACT = "http://id.tincanapi.com/attachment/contract", e.SUPPORTING_MEDIA = "http://id.tincanapi.com/attachment/supporting_media" }(e || (e = {})), function (e) { e.ABOUT = "about", e.AGENTS = "agents", e.ACTIVITIES = "activities", e.ACTIVITY_PROFILE = "activities/profile", e.STATE = "activities/state", e.AGENT_PROFILE = "agen........`

**Comment by CookieCookson** [comment]
Hi @letsgo0 thanks for logging the issue!

Can I ask how you created the Vue 3 project? Did you use the Vue CLI or did you manually add Vue / xAPI.js to an empty project? I'd like to know the steps you took to produce this issue.

The `?.` sequence is used for **Optional Chaining**, you can read more about it [here](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html). In the compiled code above it checks that `n` exists before accessing the length. Is that the unexpected token that webpack is failing to parse?

**Comment by CookieCookson** [comment]
Hi @letsgo0 I have managed to reproduce the same issue by creating a Vue 3 app using the CLI and installing `@xapi/xapi@1.0.0`. It seems that the issue indeed has come from the optional chaining, which in previous builds has been transpiled correctly by Babel.

The only difference has been that `1.0.0` was published on an M1 arm64 CPU instead of the traditional Intel-based processors. I am not sure why, but it seems to not transpile that without adding on the explicit babel plugin for optional chaining. I will republish with this fix as `1.0.1` shortly - keep your eyes peeled 👀

**Comment by letsgo0** [comment]
I used  the Vue CLI 3 to create the project. I'm not familiar with TypeScript...  
Now I get the version 1.0.1. It works.
Thanks for you work.

**Comment by CookieCookson** [comment]
Thats great, thank you for clarifying!
