### ISSUE TITLE
[Types] StatementObject should not use type Statement but new type SubStatement

### ISSUE THREAD

**Issue by FunkMonkey** [xapijs/xapi#322]
Currently [StatementObject](https://github.com/xapijs/xapi/blob/master/src/resources/statement/StatementObject.ts) is a union that includes `Statement`, which does not provide `objectType`. This leads to TS not knowing `statement.object.objectType`, which is necessary for properly determining the correct object type (even if it is just an optional property as in `Activity`).

As per [xAPI specification](https://github.com/adlnet/xAPI-Spec/blob/master/xAPI-Data.md#substatements) a `SubStatement` should be used though:
> A SubStatement MUST specify an "objectType" property with the value SubStatement.

A new interface `SubStatement` should be added and used for `StatementObject`, e.g. 

```ts
export interface SubStatement extends Statement {
  objectType: "SubStatement"
}
```

```ts
export type StatementObject =
  | Activity
  | InteractionActivity
  | ObjectiveActivity
  | Actor
  | StatementRef
  | SubStatement;
```

Thanks!

**Comment by CookieCookson** [comment]
@FunkMonkey thank you for using xAPI.js and for raising this issue!

You're right, the usage of a `Statement` within a `Statement` object should be a `SubStatement` and not just a standard `Statement`, with the inclusion of the `objectType` property. The spec also identifies that it should not contain the `id`, `stored`, `version` or `authority` properties or a nested `SubStatement`. I will see what I can do to best represent this in the Interfaces.
