### ISSUE TITLE
[Types] Minor deviations from the xAPI spec

### ISSUE THREAD

**Issue by FunkMonkey** [xapijs/xapi#325]
Thanks for fixing #322 so quickly!

While we're at it: I found some additional minor deviations from the [spec](https://github.com/adlnet/xAPI-Spec/blob/master/xAPI-Data.md):
- [ ] technically `objectType` (`Actor`) is optional for Agents (unless they are used as Objects)
- [ ] `objectType` is optional in `Activity`
- [ ] it should be `member` (singular) in `Group`
- [ ] `member` is required for Anonymous Group (though not Identified Group) 
- [ ] `homePage` and `name` are required in `Account`
- [ ] `display` is only recommended in `Verb` and thus should be optional
- [ ] `moreInfo` is missing in `ActivityDefinition`

Additionally it may be nice to have:
- [ ] Inverse Functional Identifier as its own interface that `ActorBase` would extend

Thanks a lot!

**Comment by CookieCookson** [comment]
Thanks for the helpful feedback @FunkMonkey, I'll pick these up when I can!

**Comment by CookieCookson** [comment]
@FunkMonkey The above deviations (And one or two extras I spotted) have now been actioned and are available in v2.2.2.
