### ISSUE TITLE
I'm a bit confused about the implementation of XAPI.d.ts

### ISSUE THREAD

**Issue by eMelgooG** [xapijs/xapi#58]
In this repo all the functions inside the class XAPI.d.ts are implemented, while in the package installed via npm, @xapi/xapi inside XAPI.d.ts it has the methods with the same signature, just that they are not implemented (abstract methods). Is there any reason for this? I'm trying to make an xApi wrapper with Angular and it's native HttpClient.

**Comment by CookieCookson** [comment]
Hi @eMelgooG, could you share an example snippet of how you are trying to use the library?

There are some static helper methods exposed on the XAPI class itself, but the majority of methods require you to initialise a new instance of the class to use.

The XAPI.d.ts file is only there to explain the implementation, when importing the project you will either use XAPI.cjs.js, XAPI.esm.js or XAPI.umd.js which contain the implementations themselves. Your bundler should automatically choose the correct file for you.

There is working demo of using the library as an npm package at https://github.com/xapijs/xapi-demo which might better demonstrate how to use it.

I hope this answers your question.

**Comment by eMelgooG** [comment]
Hei @CookieCookson. Thanks for your detailed answer. I managed to understand what's up with that XAPI.d.ts file just now and it's exactly as you said. Sorry for that... I am a quite new to typescript and web development. I will have a look over that demo as soon as I can. 
Basically I'm trying to set up xApi wrapper in Angular using the native Angular HttpClient instead of Axios. And maybe work with Promises and Observables instead of AxiosPromise's. Although I'm not sure yet if it's worth the struggle. 
Do you have any insights? Is it worth the struggle to implement the native HttpClient from Angular or just leave it as it is.  

I'll share a snippet of what I'm trying to do after I get a demo LRS to make some tests. I'm quite new to xApi as well and I'll be damn but the documentation is huge.

**Comment by CookieCookson** [comment]
No problem! The xAPI.js library has been written with Axios deeply embedded inside for all requests, if you wanted to use Angular HttpClient you would have to rewrite a core part of the library. You are better off working with the `AxiosPromise` responses, they behave in a very similar way to Angular's HttpClient, but with a slightly different schema. All of the data returned from the LRS should be in the responses' `data` property.

I can recommend using [SCORM Cloud](https://cloud.scorm.com/) as a demo LRS, this library has been tested extensively against that - and also [Veracity](https://lrs.io/). Both of which have free options!

I'd love to get your feedback on the documentation for this library, it does fall short on what things are intended to do but I was hoping people would use the xAPI Specification for those answers.

**Comment by eMelgooG** [comment]
I managed to set up the demo project you were talking about. I also set up an Angular demo project with this package to send statements to the Scorm Cloud LRS. I saw that in order to use the xApi wrapper in the project I have to create an instance of XAPI with the endpoint and the auth object. I was wondering if there is any way we can change this configuration without creating a new instance of the XAPI class, like in the original xApiwrapper.js from ADL.net.   
Like here:
`var conf = {
  "endpoint" : "https://lrs.adlnet.gov/xapi/",
  "auth" : "Basic " + toBase64('tom:1234'),
};
ADL.XAPIWrapper.changeConfig(conf);`

If you want to have a look over the Angular demo project:
https://stackblitz.com/edit/angular-ivy-w53ent

As for the documentation I feel like it's very good and detailed. I researched a lot and I found this to be the only xApi library in TS with proper documentation. Thanks for that.

**Comment by CookieCookson** [comment]
I have wondered about creating methods for updating the configuration after instantiation. At the moment there is no way of doing this, and would love to hear a use case for it. I cannot see it hurting to have these extra methods, but on the flip-side I don't want to implement this and document it if its ultimately pointless 🤷‍♂️ 

The project looks good, just be careful exposing code snippets with your auth credentials in 😉

**Comment by eMelgooG** [comment]
I agree with you. I tried thinking of a real word scenario where we could use this but at the moment I cannot find. Actually in some cases it might even be better to create it through a constructor especially if we have more than one Activity Provider in our app. I will work for a few months with xApi and if I'm going to see that is needed I will try implementing it and open a pr.   

As for the demo, I'm glad you like it.  I didn't cared much about the Activity Provider creds because I deleted it already from Scorm Cloud and I used it just to make a demonstration. Thanks for the tip!   

Now I'll focus on creating a LRS in C# and set up HTTP endpoints using .net web api, if you have any experience with creating an in-house LRS or any tip for this I'll be glad to hear it.   
Thanks again mate!

**Comment by CookieCookson** [comment]
No problem.

I think making an LRS is a big undertaking and I'd recommend using one off the shelf. If you want to spin up your own instance, check out https://docs.learninglocker.net/welcome/

I'm going to close down this issue now, I wish you good luck with your project!
